version: "3.9"

services:
  database:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_USER: bukku
      MYSQL_ROOT_PASSWORD: bukku
      MYSQL_DATABASE: bukku
      MYSQL_USER: bukku
      MYSQL_PASSWORD: bukku
    cap_add:
      - SYS_NICE
    ports:
      - "3308:3306"
