# fly.toml app configuration file generated for bukku-backend on 2024-01-01T15:24:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bukku-backend"
primary_region = "nrt"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health-check"
    timeout = "10s"
    type = "http"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
